
import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Progress } from '@/components/ui/progress';
import { Badge } from '@/components/ui/badge';
import { BarChart3, FileText, Code, Target } from 'lucide-react';

export const CoverageReport = () => {
  const coverageData = {
    overall: 85,
    statements: 87,
    branches: 82,
    functions: 89,
    lines: 85
  };

  const filesCoverage = [
    { file: 'src/components/UserCard.tsx', coverage: 95, status: 'excellent' },
    { file: 'src/components/LoginForm.tsx', coverage: 88, status: 'good' },
    { file: 'src/utils/helpers.ts', coverage: 92, status: 'excellent' },
    { file: 'src/services/api.ts', coverage: 76, status: 'needs-improvement' },
    { file: 'src/hooks/useAuth.ts', coverage: 82, status: 'good' },
    { file: 'src/components/Dashboard.tsx', coverage: 69, status: 'needs-improvement' }
  ];

  const getCoverageColor = (coverage) => {
    if (coverage >= 90) return 'text-green-600';
    if (coverage >= 80) return 'text-yellow-600';
    return 'text-red-600';
  };

  const getCoverageStatus = (coverage) => {
    if (coverage >= 90) return { label: 'Excellent', variant: 'default', color: 'bg-green-100 text-green-800' };
    if (coverage >= 80) return { label: 'Good', variant: 'secondary', color: 'bg-yellow-100 text-yellow-800' };
    return { label: 'Needs Improvement', variant: 'destructive', color: 'bg-red-100 text-red-800' };
  };

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <BarChart3 className="h-5 w-5" />
            Test Coverage Overview
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-5 gap-4 mb-6">
            <div className="text-center">
              <div className="text-3xl font-bold text-blue-600 mb-1">{coverageData.overall}%</div>
              <div className="text-sm text-gray-600">Overall</div>
              <Progress value={coverageData.overall} className="mt-2 h-2" />
            </div>
            
            <div className="text-center">
              <div className={`text-2xl font-bold mb-1 ${getCoverageColor(coverageData.statements)}`}>
                {coverageData.statements}%
              </div>
              <div className="text-sm text-gray-600">Statements</div>
              <Progress value={coverageData.statements} className="mt-2 h-2" />
            </div>
            
            <div className="text-center">
              <div className={`text-2xl font-bold mb-1 ${getCoverageColor(coverageData.branches)}`}>
                {coverageData.branches}%
              </div>
              <div className="text-sm text-gray-600">Branches</div>
              <Progress value={coverageData.branches} className="mt-2 h-2" />
            </div>
            
            <div className="text-center">
              <div className={`text-2xl font-bold mb-1 ${getCoverageColor(coverageData.functions)}`}>
                {coverageData.functions}%
              </div>
              <div className="text-sm text-gray-600">Functions</div>
              <Progress value={coverageData.functions} className="mt-2 h-2" />
            </div>
            
            <div className="text-center">
              <div className={`text-2xl font-bold mb-1 ${getCoverageColor(coverageData.lines)}`}>
                {coverageData.lines}%
              </div>
              <div className="text-sm text-gray-600">Lines</div>
              <Progress value={coverageData.lines} className="mt-2 h-2" />
            </div>
          </div>

          <div className="space-y-2 text-sm text-gray-600">
            <div className="flex items-center gap-2">
              <Target className="h-4 w-4" />
              <span>Target: 80% minimum coverage for production</span>
            </div>
            <div className="flex items-center gap-2">
              <Code className="h-4 w-4" />
              <span>Generated by Jest coverage reporter</span>
            </div>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5" />
            File Coverage Details
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-3">
            {filesCoverage.map((file) => {
              const status = getCoverageStatus(file.coverage);
              return (
                <div key={file.file} className="flex items-center justify-between p-3 border rounded-lg">
                  <div className="flex-1">
                    <div className="font-mono text-sm">{file.file}</div>
                    <Progress value={file.coverage} className="mt-1 h-2" />
                  </div>
                  <div className="flex items-center gap-3 ml-4">
                    <span className={`text-lg font-bold ${getCoverageColor(file.coverage)}`}>
                      {file.coverage}%
                    </span>
                    <Badge className={status.color}>
                      {status.label}
                    </Badge>
                  </div>
                </div>
              );
            })}
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Coverage Configuration</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="bg-gray-50 p-4 rounded-lg font-mono text-sm">
            <div className="text-gray-600 mb-2">// jest.config.js</div>
            <pre className="text-gray-800">{`module.exports = {
  collectCoverage: true,
  coverageDirectory: "coverage",
  coveragePathIgnorePatterns: [
    "/node_modules/",
    "/build/",
    "/dist/"
  ],
  coverageReporters: [
    "text",
    "html",
    "lcov",
    "clover"
  ],
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80
    }
  },
  collectCoverageFrom: [
    "src/**/*.{js,jsx,ts,tsx}",
    "!src/index.js",
    "!src/**/*.d.ts"
  ]
};`}</pre>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};
